name: Zeros1 CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1ï¸âƒ£ Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2ï¸âƒ£ SSH into your server and deploy
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd Work-Permit   # ğŸ” Replace with actual project path
            git reset --hard
            git clean -fd
            git pull origin main  # ğŸ“¥ Pull latest code
            # PORT=${{secrets.PORT}} docker compose build  # ğŸ³ Build new images on the server
            # PORT=${{secrets.PORT}} docker compose up -d  # ğŸš€ Restart containers
            PORT=${{ secrets.PORT }} docker compose up -d --build